###

http://localhost:49408/module-one/command/demo

###

http://localhost:49408/module-one/command/example

###

http://localhost:49408/module-one/command/demo-2

###

http://localhost:49408/module-one/command/tutorial

###

http://localhost:49408/module-one/command/no-result